version: 2018.1.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal


on_success:
- ps: >-

    If (($env:APPVEYOR_REPO_BRANCH -eq "master") -and (!$env:APPVEYOR_PULL_REQUEST_NUMBER)) {

    Get-ChildItem .\FRC-Extension\Output\*.vsix | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

    }
